### ISSUE TITLE
SASS files from node_modules are not being transpiled

### ISSUE THREAD

**Issue by renanccastro** [Meteor-Community-Packages/meteor-scss#309] opened 2021-06-29 19:48 UTC
Bringing this issue here, https://github.com/meteor/meteor/issues/11499
I've confirmed it works without issues on fourseven:scss@4.12.0 and before.
Any version after breaks.

-----
I had in a SASS file the following import:

```
@import '{}/node_modules/react-credit-cards/lib/styles.scss';
```

this file is inside this folder: imports/app/checkout/ui/components/CreditCardIssuers.scss

when compiling for development, everything works, but when compiling for production it breaks

```
  message: 'Scss compiler error: Error: File to import: {}/node_modules/react-credit-cards/lib/styles.scss not found in file: undefined\n' +
    '        on line 2 of {}/imports/app/checkout/ui/components/CreditCardIssuers.scss\n' +
```
even if I symlink it to the /imports folder, it doesn't work.

fourseven:scss is at version 4.14.2

**Comment by OverflowClancy** [comment] 2021-07-04 01:59
Same issue, on updating to Meteor 2.2.

`@import '{}/node_modules/bootstrap/scss/bootstrap.scss';`

> I've confirmed it works without issues on fourseven:scss@4.12.0 and before.

Thanks for this.  Fixed my issue also (once discovered SET METEOR_OFFLINE_CATALOG=1 to prevent the update).

**Comment by OverflowClancy** [comment] 2021-07-20 09:10
Reverting to @4.12.0 now fails as a workaround.  Package will not load, as seems node-sass version has been removed.

> Failed at the node-sass@4.12.0 postinstall script.

@3.x versions are also failing at:

> Loading fourseven:scss@3.10.0...          /

**Comment by StorytellerCZ** [comment] 2021-08-09 12:31
I think this is duplicate of #308 
I have looked into this today, but wasn't able to reproduce from my local copy. I will update dependencies and publish a new release just to see if it isn't something with that.
In the meantime the include-paths test is failing, which I think might be related.

**Comment by sebastian-ruiz** [comment] 2021-08-14 09:42
@renanccastro

I am running fourseven:scss@4.14.2 and I am not getting any errors. This is without symlinking the node_modules folder. I am using METEOR@2.2.

In `client/main.scss` I have:
```scss
@import "{}/imports/app/checkout/ui/components/CreditCardIssuers";
```

and in `imports/app/checkout/ui/components/CreditCardIssuers.scss` I have:
```scss
@import '{}/node_modules/react-credit-cards/lib/styles.scss';
```
Could you tell me which operating system you are running on? I am testing on ubuntu 18.04.

**Closed** 2021-08-16 14:56 UTC
Labels: bug
